//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employees
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Contacts = new HashSet<Contact>();
            this.Passports = new HashSet<Passport>();
            this.Telephones = new HashSet<Telephone>();
            this.Photos = new HashSet<Photo>();
        }
    
        public int EmployeeId { get; set; }
        public string FamilyName { get; set; }
        public string GivenName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Title { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string TaxFileNumber { get; set; }
        public string CompanyName { get; set; }
        public string AustralianBusinessNumber { get; set; }
        public string BSBNumber { get; set; }
        public string AccountNumber { get; set; }
        public string BankName { get; set; }
        public string BankBranch { get; set; }
        public string AccountName { get; set; }
        public string SuperFundName { get; set; }
        public string MemberNumber { get; set; }
        public string QantasFrequentFlyerNumber { get; set; }
        public string VirginVelocityNumber { get; set; }
        public string EmiratesSkywardsNumber { get; set; }
        public string OthersNumber { get; set; }
    
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Passport> Passports { get; set; }
        public virtual ICollection<Telephone> Telephones { get; set; }
        public virtual ICollection<Photo> Photos { get; set; }
    }
}
