//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employees
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passport
    {
        public int PassportId { get; set; }
        public string PassportNumber { get; set; }
        public string Nationality { get; set; }
        public string VisaType { get; set; }
        public string VisaNumber { get; set; }
        public Nullable<System.DateTime> VisasIssueDate { get; set; }
        public Nullable<System.DateTime> VisasExpiryDate { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
